### ISSUE TITLE
Monorepo wioth scoped packages doesn't work 

### ISSUE THREAD

**Issue by giedrioks** [cloudfoundry/nodejs-buildpack#153]
## Summary:

We use monorepo, CF and community buildpack in our current project. 

Project structure as follows: 
```
root \
	node_modules
	packages \
		package A
		package B
		package C
	package.json
```

Yarn workspaces and lerna is used to manage dependencies in this monorepo. For packages we use scoped packages: `@some-scope/package-A`. This whole setup been working as expected till buildpack version `1.6.21` (`1.6.20` is latest which works). 

Current setup works locally, but then pushed to CF fails to find dependencies on runtime with pretty generic error:
```
   2018-07-27T16:29:31.79+0300 [APP/PROC/WEB/0] ERR Error: Cannot find module ‘@some-scope/package-A’
   2018-07-27T16:29:31.79+0300 [APP/PROC/WEB/0] ERR     at Function.Module._resolveFilename (module.js:547:15)
```

It works with below dependencies: 
Node version: `8.10`, yarn version: `1.5.1`, buildpack: `1.6.20`, lerna: `2.11.0`

But it stopped working after updating buildpack: 
Node version: `8.10`, yarn version: `1.5.1`, buildpack: `1.6.21`, lerna: `2.11.0`

There seems to be something wrong within the buildpack it self and how it handles monorepo package linking. 

We use also yarn offline mode, but I tried without it and observed same behaviour, so we can scope it out. 

## What did you expect to happen?
Yarn should install monorepo dependencies. Packages within this monorepo should be visible to one other and linked together. 

## What was the actual behavior?
Currently yarn install finishes successfully, but packages within monorepo is not visible to each other. 

## What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
`cf version 6.31.0+b35df905d.2017-09-15`

## What version of the buildpack you are using?
https://github.com/cloudfoundry/nodejs-buildpack#v1.6.21

**Comment by giedrioks** [comment]
We did further investigation on different version impact: 
- Node version: `8.10`, yarn version: `1.5.1`, buildpack: `1.6.22`, lerna: `2.11.0`
- Node version: `8.10`, yarn version: `1.6`, buildpack: `1.6.23`, lerna: `2.11.0`
- Node version: `8.10`, yarn version: `1.6`, buildpack: `1.6.24`, lerna: `2.11.0`
- Node version: `8.11.1`, yarn version: `1.7`, buildpack: `1.6.25`, lerna: `2.11.0`
- Node version: `8.11.3`, yarn version: `1.7`, buildpack: `1.6.26`, lerna: `2.11.0`
- Node version: `8.11.3`, yarn version: `1.7`, buildpack: `1.6.27`, lerna: `2.11.0`
- Node version: `8.11.3`, yarn version: `1.7`, buildpack: `1.6.28`, lerna: `2.11.0`
- Node version: `8.11.3`, yarn version: `1.7`, buildpack: `1.6.29`, lerna: `2.11.0`

All above resulted in a same issue with missing module.

**Comment by astrieanna** [comment]
@giedrioks We do rebuild native modules when `node_modules` is present. Are you not seeing a log line `rebuilding any native modules` when you push with a `node_modules` directory?

**Comment by giedrioks** [comment]
@astreanna We don't push `node_modules`. After we run `yarn install`, expected behaviour is to have modules linked to each other. This is mostly due to monorepo nature and symlinks between packages. I am not quite sure and trying to understand the reason of moving artifacts after.

**Comment by astrieanna** [comment]
The goal of those changes is to stop modifying the app directory. Buildpacks should not modify the app directory when it is possible to avoid it because modifying the directory impedes caching. Making the nodejs buildpack not modify the app directory when `node_modules` isn't vendored is a bug fix.

It sounds like you're vendoring these monorepo dependencies in a way the buildpack currently doesn't recognize, and that pushing with `node_modules` is at least a work around that causes your app to push successfully? We do `npm rebuild` modules pushed in `node_modules`, so it's fine to push native modules this way.

**Comment by jfeeny** [comment]
@giedrioks Is there a sample app you could provide for us to look into this further?

**Comment by giedrioks** [comment]
@jfeeny I can't provide real app, but will try to build some most simplest sample for you. Will post separately.

**Comment by giedrioks** [comment]
@jfeeny Please find application minimised to the minimum [here](https://github.com/giedrioks/sample-monorepo). I managed to get same error during push while starting application in CF. Let me know if you need any more details or have other questions. 

Error during push (using buildpack version `1.6.30` and node `8.11.4`): 
```
   2018-08-21T10:12:47.99+0300 [APP/PROC/WEB/0] OUT > node packages/sample-app/index.js
   2018-08-21T10:12:48.21+0300 [APP/PROC/WEB/0] ERR module.js:549
   2018-08-21T10:12:48.21+0300 [APP/PROC/WEB/0] ERR     throw err;
   2018-08-21T10:12:48.21+0300 [APP/PROC/WEB/0] ERR     ^
   2018-08-21T10:12:48.21+0300 [APP/PROC/WEB/0] ERR Error: Cannot find module '@sample/sample-config'
```

It works with buildpack version `1.6.20` (node must be downgraded to `8.9.x`).

**Comment by dagda1** [comment]
I have exactly the same issue, it cannot find the monorepo dependencies.

**Comment by giedrioks** [comment]
This should be definitely supported by buildpack IMHO. Workspace support is out of the box Yarn feature. If buildpack supports Yarn, this also should be supported and work.

**Comment by sclevine** [comment]
Thanks for the sample, this is now prioritized.

**Comment by sclevine** [comment]
@giedrioks this should be fixed on the develop branch. Can you let us know if it works for you?

`cf push myapp -b https://github.com/cloudfoundry/nodejs-buildpack#develop`

**Comment by giedrioks** [comment]
@sclevine We tried and it worked on our end.

**Comment by tylerphelan** [comment]
@jizusun the latest release will have the fix v1.6.41
